id: AFF4FCA3B
base_file: f04C3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:46:39.048705
  last_modified_at: 2022-05-30 20:46:39.048712
